version: '3'

services:
  bff:
    build: bff
    command: npm run start:dev
    environment:
      - PORT=3001
      - MELI_API_URL=https://api.mercadolibre.com
    ports:
      - 3001:3001
    volumes:
      - ./bff:/usr/src/app

  # app:
  #   build: app
  #   command: npm run start:dev
  #   depends_on:
  #     - bff
  #   environment:
  #     - PORT=3000
  #     - BFF_API_URL=http://bff:3001
  #   ports:
  #     - 3000:3000
